blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListViews, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListViews.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from users.views import UserCreateViews, UserUpdateViews

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateViews.as_view(), name="register"),
    path("update/<int:pk>/", UserUpdateViews.as_view(), name="users_update"),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок", help_text="Введите название Заголовка")
    content = models.TextField(verbose_name="Содержимое публикации", blank=True, null=True)
    photo = models.ImageField(upload_to="photo_blog/", verbose_name="Изображение", blank=True, null=True)
    created_at = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_counter = models.PositiveIntegerField(verbose_name="Количество просмотров", default=0)

    def __str__(self):
        return f"{self.title} создано: {self.created_at}, количество просмотров: {self.views_counter}"

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["title"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse

from blog.models import Blog
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView


class BlogListViews(ListView):
    model = Blog
    template_name = "blog_list.html"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.paginate_by:
            paginator = context["paginator"]
            context["is_paginated"] = paginator.num_pages > 1
        return context

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ["title", "photo", "content", "is_published"]
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.add_blog"


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.delete_blog"


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ["title", "photo", "content", "is_published"]
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.change_blog"

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])

blog/templates/blog/includes/inc_menu.html
 <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

blog/templates/blog/includes/top_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
    </nav>
    <div class="d-flex justify-content-end">
<nav class="ms-5">
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_update' user.pk %}">Редактирование профиля</a>
            <form method="post" action="{% url 'users:logout' %}" style="display: inline">
                {% csrf_token %}
                 <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
            </form>

    {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
    {% endif %}
</nav>
    </div>
</div>