blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListViews, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListViews.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок", help_text="Введите название Заголовка")
    content = models.TextField(verbose_name="Содержимое публикации", blank=True, null=True)
    photo = models.ImageField(upload_to="photo_blog/", verbose_name="Изображение", blank=True, null=True)
    created_at = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_counter = models.PositiveIntegerField(verbose_name="Количество просмотров", default=0)

    def __str__(self):
        return f"{self.title} создано: {self.created_at}, количество просмотров: {self.views_counter}"

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ["title"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse

from blog.models import Blog
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView


class BlogListViews(ListView):
    model = Blog
    template_name = "blog_list.html"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.paginate_by:
            paginator = context["paginator"]
            context["is_paginated"] = paginator.num_pages > 1
        return context

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ["title", "photo", "content", "is_published"]
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.add_blog"


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.delete_blog"


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ["title", "photo", "content", "is_published"]
    success_url = reverse_lazy("blog:blog_list")
    permission_required = "blog.change_blog"

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-6">
       <form class="row" method="post" enctype="multipart/form-data">
         <div class="card">
              <p class="card-text">Действительно хотите удалить статью: {{ object.title }}</p>
             <div class="card-body">
                 {% csrf_token %}
             </div>
             <button type="submit" class="btn btn-primary">
                 Удалить
             </button>
             <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
         </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/home.html' %}
{% load my_tag %}
{% block content %}

<div class="container">

    <div class="row text-center">
        <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
                <div class="card-header">
                    <img class="rounded mx-auto d-block" src="{{ blog.photo | media_filter }}" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ blog.title }}</h1>
                    <h3 class="card-title pricing-card-title">Количество просмотров: {{ blog.views_counter }}</h3>
                    <p>Дата создания: {{ blog.created_at | date:"d M Y" }}</p>
                    <p>Описание: {{ blog.content }}</p>
                    <p>Статус:
                        {% if blog.is_published %}
                            Опубликовано
                         {% else %}
                             Не опубликовано
                        {% endif %}
                        </p>
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Каталог статей</a>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/home.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>{% if object %}
     Редактировать статью
     {% else %}
     Новый статья
     {% endif %}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Выводим форму -->

        <button type="submit" class="btn btn-primary">
                 {% if object %}
                 Сохранить
                 {% else %}
                 Добавить
                {% endif %}
             </button>
         <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
    </ul>
    </form>
</body>
</html>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/home.html' %}
{% load my_tag %}
{% block content %}

<div class="album py-5 bg-body-tertiary">

    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for art in object_list %}
            <div class="col-3">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header">
                    <h1 class="card-title pricing-card-title">{{ art.title }}</h1>
                   <img class="card-img-top" src="{{ art.photo | media_filter }}" alt="Card image cap">-->
                    <p>Количество просмотров: {{ art.views_counter }}</p>
                </div>
                <div class="card-body">
                    <p>Содержание статьи: {{ art.content | truncatechars:100 }}</p>
                   <a class="btn btn-primary" href="{% url 'blog:blog_detail' art.pk %}" role="button">Читать статью</a>
                    {% if "blog.change_blog" in perms %}
                    <a class="btn btn-primary" href="{% url 'blog:blog_update' art.pk %}" role="button">Изменить статью</a>
                    {% endif %}
                    {% if "blog.change_blog" in perms %}
                    <a class="btn btn-primary" href="{% url 'blog:blog_delete' art.pk %}" role="button">Удалить статью</a>
                    {% endif %}

                </div>
            </div>

        </div>
 {% endfor %}
    </div>

</div>

</div>
 {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">« Предыдущая</a>
                    </li>
                {% endif %}

                {% for num in page_numbers %}
                    <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая »</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/home.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/>

</head>
<body>
{% include 'blog/includes/top_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блок</h1>
    <p class="lead">Блок статьей о чем-то или о ком-то, в общем-то не так уж и важно о чем</p>
</div>
   {% if "blog.add_blog" in perms %}
<div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
         <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'blog:blog_create' %}">Добавить новую статью</a>
      </div>
{% endif %}
{% block content %}
{% endblock %}

{% include 'blog/includes/inc_menu.html' %}


<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>