blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListViews, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path("", BlogListViews.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("blog/create/", BlogCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name="blog_delete"),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name="blog_update"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import (
    CatalogListViews,
    ContactViews,
    CatalogDetailViews,
    CatalogCreateView,
    CatalogDeleteView,
    CatalogUpdateView,
    UnpublishProductView,
    CategoryListViews,
    CategoryProductsDetailView,
)


app_name = CatalogConfig.name

urlpatterns = [
    path("", CatalogListViews.as_view(), name="product_list"),
    path("catalog/<int:pk>/", cache_page(60 * 10)(CatalogDetailViews.as_view()), name="product_detail"),
    path("contacts/", ContactViews.as_view(), name="contacts"),
    path("catalog/create/", CatalogCreateView.as_view(), name="product_create"),
    path("catalog/<int:pk>/delete/", CatalogDeleteView.as_view(), name="product_delete"),
    path("catalog/<int:pk>/update/", CatalogUpdateView.as_view(), name="product_update"),
    path("catalog/unpublish/<int:pk>/", UnpublishProductView.as_view(), name="unpublish_product"),
    path("catalog/category/", CategoryListViews.as_view(), name="category_list"),
    path(
        "catalog/product_category/<int:pk>/",
        cache_page(60 * 10)(CategoryProductsDetailView.as_view()),
        name="product_category",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from catalog.validator import FileSizeValidator, ImageFormatValidator
from users.models import User


class Category(models.Model):
    """Класс для создания модели(таблицы) Категория"""

    name = models.CharField(max_length=50, verbose_name="Категория", help_text="Введите название категории")
    description = models.TextField(
        verbose_name="Описание категории", help_text="Введите описание категории", blank=True, null=True
    )

    def __str__(self):
        """Метод для строкового отображения информации о категории"""
        return self.name

    class Meta:
        """Данный класс используется для добавления метаданных к модели:
        наименование модели в единственном и множественном числе"""

        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    """Класс для создания модели(таблицы) Продукции"""

    name = models.CharField(max_length=50, verbose_name="Товар", help_text="Введите название товара")
    description = models.TextField(
        verbose_name="Описание товара", help_text="Введите описание товара", blank=True, null=True
    )
    photo_product = models.ImageField(
        upload_to="photos/",
        validators=[FileSizeValidator(), ImageFormatValidator()],
        verbose_name="Изображение",
        blank=True,
        null=True,
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена", help_text="Укажите цену за покупку товара", default=0
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        help_text="Введите категорию товара",
        blank=True,
        null=True,
        related_name="products",
    )
    created_at = models.DateField(verbose_name="Дата создания", auto_now_add=True)
    updated_at = models.DateField(verbose_name="Дата последнего изменения", auto_now=True)

    is_published = models.BooleanField(default=False, verbose_name="Статус публикации")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Укажите владельца собаки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        """Метод для строкового отображения информации о продукте"""
        return f"{self.name}, относится к категории {self.category}, цена: {self.price}"

    class Meta:
        """Данный класс используется для добавления метаданных к модели:
        наименование модели в единственном и множественном числе,
        а также порядок сортировки продукции при выборке из БД"""

        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name", "category", "price"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]


class Contact(models.Model):
    """Класс для создания модели(таблицы) контакты"""

    country = models.CharField(max_length=50, verbose_name="Страна", help_text="Введите название страны")
    address = models.CharField(
        max_length=150, verbose_name="Адрес", help_text="Введите Ваш адрес", blank=True, null=True
    )
    individual_tax_index = models.IntegerField(verbose_name="ИНН", blank=True, null=True)

    def __str__(self):
        """Метод для строкового отображения информации о контактах"""
        return f"{self.country}, {self.address}"

    class Meta:
        """Данный класс используется для добавления метаданных к модели:
        наименование модели в единственном и множественном числе"""

        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

catalog/forms.py
from django.forms import ModelForm, BooleanField
from django.core.exceptions import ValidationError


from catalog.models import Product

EXCEPTION_WORDS = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]


class StyleFormMixin:
    """Стилизация форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs["class"] = "form-check-input"
            else:
                fild.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, ModelForm):
    """Класс для создания формы (добавления нового товара)"""

    class Meta:
        model = Product
        fields = ["name", "description", "photo_product", "category", "price"]

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name.lower() in EXCEPTION_WORDS:
            raise ValidationError(f"Вы ввели запрещенное слово {name}! Исправляйтесь!!!")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")

        for word in EXCEPTION_WORDS:
            if word in description.lower():
                raise ValidationError(f"Вы ввели запрещенное слово {word}! Исправляйтесь!!!")
        return description

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError(
                "Цена ниже плинтуса!!! Мы не можем работать в убыток!!! Будьте любезны исправить это НЕМЕДЛЕНО!"
            )
        return price

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.core.cache import cache

from catalog.forms import ProductForm
from django.urls import reverse_lazy, reverse
from catalog.models import Product, Contact, Category
from django.views.generic import ListView, DetailView, TemplateView, CreateView, DeleteView, UpdateView, View
from catalog.services import get_products_by_category


class CategoryListViews(ListView):
    model = Category
    template_name = "category_list.html"


class CategoryProductsDetailView(DetailView):
    model = Category
    template_name = "catalog/product_category.html"

    def get_context_data(self, **kwargs):
        # Получаем стандартный контекст данных из родительского класса
        context = super().get_context_data(**kwargs)
        # Получаем ID категории из объекта
        category = self.object.id
        context["products_category"] = get_products_by_category(category)
        return context


class UnpublishProductView(LoginRequiredMixin, View):

    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)

        if not request.user.has_perm("catalog.can_unpublish_product"):
            raise PermissionDenied("У вас нет права на отмену публикации продукции")

        product.is_published = False
        product.save()

        return redirect("catalog:product_detail", pk=pk)


class CatalogListViews(ListView):
    model = Product
    template_name = "product_list.html"
    paginate_by = 3

    def get_queryset(self):
        queryset = cache.get("product_queryset")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("product_queryset", queryset, 60 * 10)  # Кешируем данные на 10 минут
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.paginate_by:
            paginator = context["paginator"]
            context["is_paginated"] = paginator.num_pages > 1
        return context


class ContactViews(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            name = self.request.POST.get("name")
            message = self.request.POST.get("message")
            phone = self.request.POST.get("phone")
            print(f"POST-запрос от пользователя: {name}, тел: {phone}, сообщение: {message}")
        context_data["contact"] = Contact.objects.all()[0]
        return context_data


class CatalogDetailViews(DetailView):
    model = Product


class CatalogCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class CatalogUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        user = self.request.user

        if product.owner != user:
            raise PermissionDenied

        return product


class CatalogDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        user = self.request.user

        if product.owner != user and not user.has_perm("catalog.delete_product"):
            raise PermissionDenied

        return product

catalog/templates/catalog/add_product.html
{% extends 'catalog/base.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>Новый продукт</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Выводим форму -->

        <button type="submit">Добавить</button>
    </ul>
{% endif %}
    </form>
</body>
</html>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"/>

</head>
<body>
{% include 'catalog/includes/top_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

{% block content %}
{% endblock %}

{% include 'catalog/includes/inc_menu.html' %}


<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="album py-5 bg-body-tertiary">

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"> Выберите интересующую Вас категорию</h1>

</div>
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for category in category_list %}
            <div class="col-3">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header">
                    <h1 class="card-title pricing-card-title">{{ category.name }}</h1>
                </div>
                <div class="card-body">
                    <p>Описание: {{ category.description | truncatechars:100 }}</p>

                </div>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
                <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'catalog:product_category' category.id %}">Перейти</a>
                </div>
            </div>

            </div>
            {% endfor %}
    </div>

</div>

</div>

</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ contact.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ contact.individual_tax_index }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ contact.address }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

catalog/templates/catalog/product_category.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
    <h1>Продукты в категории {{ object.name }}</h1>
        </div>
    <ul>
    {% if products_category %}
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in products_category %}
            <div class="col-3">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header">
                    <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                   <img class="card-img-top" src="{{ product.photo_product | media_filter }}" alt="Card image cap">-->
                </div>
                <div class="card-body">
                    <p>Описание: {{ product.description | truncatechars:100 }}</p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
                     {% if product.owner == user %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                    <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    {% endif %}
                     <form action="{% url 'catalog:unpublish_product' product.pk %}" method="post">
                        {% csrf_token %}
                         <button class="btn btn-primary">Отмена публикации продукта</button>
                    </form>


                    {% endif %}
                </div>
            </div>

            </div>
            {% endfor %}
    </div>

    </div>

    {% else %}
            <li>Нет доступных продуктов в этой категории.</li>
        {% endif %}
    </ul>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'catalog:category_list' %}">Назад</a>
        </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-6">
       <form class="row" method="post" enctype="multipart/form-data">
         <div class="card">
              <p class="card-text">Действительно хотите удалить {{ object.name }}</p>
             <div class="card-body">
                 {% csrf_token %}
             </div>
             <button type="submit" class="btn btn-primary">
                 Удалить
             </button>
             <a class="btn btn-primary" href="{% url 'catalog:product_list'%}" role="button">Отмена</a>
         </div>
        </form>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}

<div class="container">

    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <img class="card-img-top" src="{{ product.photo_product | media_filter }}" alt="Card image cap">
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                    <h2 class="card-title pricing-card-title">{{ product.price }} руб.</h2>
                    <p>Категория: {{ product.category }}</p>
                    <p>Описание: {{ product.description }}</p>
                    {% if not product.is_published %}
                        <p>Продукт снят с публикации</p>
                    {% endif %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Каталог</a>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
 <h1>{% if object %}
     Редактировать информацию о продукте
     {% else %}
     Новый продукт
     {% endif %}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            <div>{{ field }}</div>
            {% if field.errors%}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}


        <button type="submit">
             {% if object %}
                 Сохранить
                 {% else %}
                 Добавить
                {% endif %}
        </button>
         <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
    </ul>

    </form>
  </div>
</body>
</html>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}

<div class="album py-5 bg-body-tertiary">

    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for product in object_list %}
            <div class="col-3">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header">
                    <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                   <img class="card-img-top" src="{{ product.photo_product | media_filter }}" alt="Card image cap">-->
                </div>
                <div class="card-body">
                    <p>Описание: {{ product.description | truncatechars:100 }}</p>
                    {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
                     {% if product.owner == user %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                    <a class="btn btn-primary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    {% endif %}
                     <form action="{% url 'catalog:unpublish_product' product.pk %}" method="post">
                        {% csrf_token %}
                         <button class="btn btn-primary">Отмена публикации продукта</button>
                    </form>


                    {% endif %}
                </div>
            </div>

            </div>
            {% endfor %}
    </div>

</div>

</div>
 {% if is_paginated %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center mt-4">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">« Предыдущая</a>
                    </li>
                {% endif %}

                {% for num in page_numbers %}
                    <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая »</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock %}